### ISSUE TITLE
Ignore .git directory for repos who use git as a backup/versioning system

### ISSUE THREAD

**Issue by SlyBouhafs** [kanru/logseq-encrypt-ui#1]
Hi,

I noticed that logseq-encrypt-ui doesn't ignore the `.git` directory when scanning for encrypted files, which takes a lot of time. Is it possible to avoid scanning the `.git` directory to make it a little bit faster?

**Comment by kanru** [comment]
Good idea! I think it should ignore all hidden directory since Logseq doesn't use one.
